/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_databace_disen_coughlan;
import classes.student;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author disen
 */
public class addStudentResultsFrame extends javax.swing.JFrame {

    /**
     * Creates new form addStudentResultsFrame
     */
    public addStudentResultsFrame() {
        initComponents();
    }
    student s1 = new student();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuB = new javax.swing.JButton();
        classGroupCb = new javax.swing.JComboBox<>();
        classGroupL = new javax.swing.JLabel();
        studentIdL = new javax.swing.JLabel();
        saveAndAddB = new javax.swing.JButton();
        assment1L = new javax.swing.JLabel();
        assment2L = new javax.swing.JLabel();
        assment3L = new javax.swing.JLabel();
        examL = new javax.swing.JLabel();
        assment1Tf = new javax.swing.JTextField();
        assment2Tf = new javax.swing.JTextField();
        assment3Tf = new javax.swing.JTextField();
        examTf = new javax.swing.JTextField();
        modulesL = new javax.swing.JLabel();
        studentIdLi = new java.awt.List();
        modulesLi = new java.awt.List();
        searchB = new javax.swing.JButton();
        clearListB = new javax.swing.JButton();
        studentNameLi = new java.awt.List();
        studentNameL = new javax.swing.JLabel();
        modulesNamesLi = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(80, 200, 120));

        menuB.setText("back to menu");
        menuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBActionPerformed(evt);
            }
        });

        classGroupL.setText("class group");

        studentIdL.setText("student id");

        saveAndAddB.setText("save and add");
        saveAndAddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndAddBActionPerformed(evt);
            }
        });

        assment1L.setText("assment 1");
        assment1L.setVisible(false);

        assment2L.setText("assment 2");
        assment2L.setVisible(false);

        assment3L.setText("assment 3");
        assment3L.setVisible(false);

        examL.setText("exam");
        examL.setVisible(false);

        assment1Tf.setVisible(false);

        assment2Tf.setVisible(false);

        assment3Tf.setVisible(false);

        examTf.setVisible(false);

        modulesL.setText("modules");

        searchB.setText("search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        clearListB.setText("clear list");
        clearListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListBActionPerformed(evt);
            }
        });

        studentNameLi.setEnabled(false);

        studentNameL.setText("student name");

        modulesNamesLi.setEnabled(false);

        jLabel1.setText("modules names");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(classGroupL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(studentIdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(studentNameLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 224, Short.MAX_VALUE)
                                        .addComponent(studentNameL)
                                        .addGap(81, 81, 81)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(modulesL)
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(modulesLi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modulesNamesLi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(assment2L)
                                            .addComponent(assment3L)
                                            .addComponent(examL, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(assment1L))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(assment1Tf)
                                            .addComponent(assment2Tf)
                                            .addComponent(assment3Tf)
                                            .addComponent(examTf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                                        .addComponent(saveAndAddB)
                                        .addGap(52, 52, 52)))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentIdL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuB)
                .addGap(18, 18, 18)
                .addComponent(clearListB)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(classGroupL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classGroupCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchB))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdL, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modulesL)
                    .addComponent(studentNameL)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentNameLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 168, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assment1Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assment1L))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assment2L, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(assment2Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assment3L)
                            .addComponent(assment3Tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(examL)
                            .addComponent(examTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(saveAndAddB))
                    .addComponent(studentIdLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulesLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulesNamesLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearListB)
                    .addComponent(menuB))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBActionPerformed
        teacherFrame teacherFrame = new teacherFrame();
        teacherFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        studentIdLi.removeAll();
        modulesLi.removeAll();
        studentNameLi.removeAll();
        modulesNamesLi.removeAll();
        try{
String url = "jdbc:mysql://127.0.0.1:3306/";
String dbName = "college";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "987456321Dc";
  //Class.forName(driver).newInstance();
          Connection conn = DriverManager.getConnection(url+dbName,userName,password);
//Connection con = DriverManager.getConnection(host);
 PreparedStatement prest;
//SQL
String sql = "SELECT * FROM students WHERE class_group_id = ?";
 
prest = conn.prepareStatement(sql);
prest.setString(1, classGroupCb.getSelectedItem().toString());
       //Results of the sql stored in the resultSet rs1
        ResultSet rs1 = prest.executeQuery();
//This will loop and show all the results from the sql query
while (rs1.next()){
    
        String student_id = rs1.getString(1);
        String value = ("Student Id  : " + student_id );
        System.out.println( value);
        String first_name = rs1.getString(2);
        String value2 = ("Student Name  : " + first_name );
        System.out.println( value2);
        String lastName = rs1.getString(3);
        String value3 = ("Last name :" + lastName);
        System.out.println( value3);
        studentIdLi.add((rs1.getObject(1)+""));
        studentNameLi.add((rs1.getObject(2)+"")+" "+(rs1.getObject(3)+""));
            }
}
catch (SQLException err) {
  System.out.println(err.getMessage());
}
         try{
String url = "jdbc:mysql://127.0.0.1:3306/";
String dbName = "college";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "987456321Dc";
  //Class.forName(driver).newInstance();
          Connection conn = DriverManager.getConnection(url+dbName,userName,password);
//Connection con = DriverManager.getConnection(host);
 PreparedStatement prest;
//SQL
String sql = "SELECT distinct module.module_id,module.module_name "
           + "FROM students,module,class_group,course,module_course "
           + "WHERE students.class_group_id = ? "
           + "and students.class_group_id = class_group.class_group_id "
           + "and class_group.course_id = course.course_id "
           + "and course.course_id = module_course.course_id "
           + "and module_course.module_id = module.module_id;";
 
prest = conn.prepareStatement(sql);
prest.setString(1, classGroupCb.getSelectedItem().toString());
       //Results of the sql stored in the resultSet rs1
        ResultSet rs1 = prest.executeQuery();
//This will loop and show all the results from the sql query
while (rs1.next()){
    
        String module_id = rs1.getString(1);
        String value = ("Module Id  : " + module_id );
        System.out.println( value);
        
        String module_name = rs1.getString(2);
        String value2 = ("Module name  : " + module_name );
        System.out.println( value2);
        
        modulesLi.add((rs1.getObject(1)+""));
        modulesNamesLi.add((rs1.getObject(2)+""));
            }
}
catch (SQLException err) {
  System.out.println(err.getMessage());
}
         assment1L.setVisible(true);
         assment1Tf.setVisible(true);
         assment2L.setVisible(true);
         assment2Tf.setVisible(true);
         assment3L.setVisible(true);
         assment3Tf.setVisible(true);
         examL.setVisible(true);
         examTf.setVisible(true);
        
    }//GEN-LAST:event_searchBActionPerformed

    private void clearListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearListBActionPerformed
        studentIdLi.removeAll();
        modulesLi.removeAll();
        studentNameLi.removeAll();
        modulesNamesLi.removeAll();
    }//GEN-LAST:event_clearListBActionPerformed

    private void saveAndAddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndAddBActionPerformed
        try{
            double ass1 = student.getDouble(assment1Tf.getText());
            double ass2 = student.getDouble(assment2Tf.getText());
            double ass3 = student.getDouble(assment3Tf.getText());
            double exam = student.getDouble(examTf.getText());
            s1.setGrade(ass1, ass2, ass3, exam);
String url = "jdbc:mysql://127.0.0.1:3306/";
String dbName = "college";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "987456321Dc";
  //Class.forName(driver).newInstance();
          Connection conn = DriverManager.getConnection(url+dbName,userName,password);
//Connection con = DriverManager.getConnection(host);
 PreparedStatement prest;
//SQL
String sql = "insert into students_results (student_id,class_group_id,module_id,assment_1,assment_2,assment_3,exam,grade)\n" +
"values (?,?,?,?,?,?,?,?);";
 
prest = conn.prepareStatement(sql);
prest.setString(1,studentIdLi.getSelectedItem().toString());
prest.setString(2,classGroupCb.getSelectedItem().toString());
prest.setString(3,modulesLi.getSelectedItem().toString());
prest.setString(4,assment1Tf.getText());
prest.setString(5,assment2Tf.getText());
prest.setString(6,assment3Tf.getText());
prest.setString(7,examTf.getText());
prest.setString(8,s1.getGrade());
System.out.println("works");
prest.executeUpdate();
conn.close();
        }
    catch(SQLException err){
        System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_saveAndAddBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         try{
String url = "jdbc:mysql://127.0.0.1:3306/";
String dbName = "college";
          String driver = "com.mysql.jdbc.Driver";
          String userName = "root";
          String password = "987456321Dc";
  //Class.forName(driver).newInstance();
          Connection conn = DriverManager.getConnection(url+dbName,userName,password);
//Connection con = DriverManager.getConnection(host);
 PreparedStatement prest;
//SQL
String sql = "select distinct class_group.class_group_id from class_group;";
prest = conn.prepareStatement(sql);
       //Results of the sql stored in the resultSet rs1
        ResultSet rs1 = prest.executeQuery();
//This will loop and show all the results from the sql query
while (rs1.next()){
    
        classGroupCb.addItem(rs1.getObject(1)+"");
            }
}
catch (SQLException err) {
  System.out.println(err.getMessage());
}
    }//GEN-LAST:event_formWindowActivated
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudentResultsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudentResultsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudentResultsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudentResultsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudentResultsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assment1L;
    private javax.swing.JTextField assment1Tf;
    private javax.swing.JLabel assment2L;
    private javax.swing.JTextField assment2Tf;
    private javax.swing.JLabel assment3L;
    private javax.swing.JTextField assment3Tf;
    private javax.swing.JComboBox<String> classGroupCb;
    private javax.swing.JLabel classGroupL;
    private javax.swing.JButton clearListB;
    private javax.swing.JLabel examL;
    private javax.swing.JTextField examTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menuB;
    private javax.swing.JLabel modulesL;
    private java.awt.List modulesLi;
    private java.awt.List modulesNamesLi;
    private javax.swing.JButton saveAndAddB;
    private javax.swing.JButton searchB;
    private javax.swing.JLabel studentIdL;
    private java.awt.List studentIdLi;
    private javax.swing.JLabel studentNameL;
    private java.awt.List studentNameLi;
    // End of variables declaration//GEN-END:variables
}
