/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college_databace_disen_coughlan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author disen
 */
public class showStudentRecordFrame extends javax.swing.JFrame {

    /**
     * Creates new form showStudentRecordFrame
     */
    public showStudentRecordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuB = new javax.swing.JButton();
        studentNameLi = new java.awt.List();
        classGroupLi = new java.awt.List();
        modulesLi = new java.awt.List();
        assmentsLi = new java.awt.List();
        examsLi = new java.awt.List();
        gradeLi = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        studentIdLi = new java.awt.List();
        searchB = new javax.swing.JButton();
        clearB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(80, 200, 120));

        menuB.setText("back to menu");
        menuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("class group");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("modules");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("assments");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("exams");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("grade");

        searchB.setText("search");
        searchB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBActionPerformed(evt);
            }
        });

        clearB.setText("clear");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(studentIdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(menuB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clearB)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(studentNameLi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classGroupLi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modulesLi, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(assmentsLi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(examsLi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(gradeLi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(searchB)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(searchB))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentIdLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classGroupLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modulesLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assmentsLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examsLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gradeLi, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuB)
                    .addComponent(clearB)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBActionPerformed
        teacherFrame teacherFrame = new teacherFrame();
        teacherFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBActionPerformed

    private void searchBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBActionPerformed
        studentNameLi.removeAll();
        classGroupLi.removeAll();
        modulesLi.removeAll();
        assmentsLi.removeAll();
        examsLi.removeAll();
        gradeLi.removeAll();
        try{
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "college";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "987456321Dc";
            //Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url+dbName,userName,password);
            //Connection con = DriverManager.getConnection(host);
            PreparedStatement prest;
            //SQL
            String sql = "SELECT * FROM college.students WHERE student_id = ? ;";

            prest = conn.prepareStatement(sql);
            prest.setString(1,studentIdLi.getSelectedItem().toString());
            //Results of the sql stored in the resultSet rs1
            ResultSet rs1 = prest.executeQuery();
            //This will loop and show all the results from the sql query
            while (rs1.next()){

                studentNameLi.add((rs1.getObject(2)+"")+" "+(rs1.getObject(3)+""));
                classGroupLi.add((rs1.getObject(10)+""));
            }
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
        try{
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "college";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "987456321Dc";
            //Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url+dbName,userName,password);
            //Connection con = DriverManager.getConnection(host);
            PreparedStatement prest;
            //SQL
            String sql = "SELECT distinct module.module_id,module.module_name "
            + "FROM students,module,class_group,course,module_course "
            + "WHERE students.student_id = ? "
            + "and students.class_group_id = class_group.class_group_id "
            + "and class_group.course_id = course.course_id "
            + "and course.course_id = module_course.course_id "
            + "and module_course.module_id = module.module_id;";

            prest = conn.prepareStatement(sql);
            prest.setString(1, studentIdLi.getSelectedItem().toString());
            //Results of the sql stored in the resultSet rs1
            ResultSet rs1 = prest.executeQuery();
            //This will loop and show all the results from the sql query
            while (rs1.next()){

                String module_id = rs1.getString(1);
                String value = ("Module Id  : " + module_id );
                System.out.println( value);

                String module_name = rs1.getString(2);
                String value2 = ("Module name  : " + module_name );
                System.out.println( value2);

                modulesLi.add((rs1.getObject(1)+"")+ " " + (rs1.getObject(2)+""));
                
            }
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
        try{
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "college";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "987456321Dc";
            //Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url+dbName,userName,password);
            //Connection con = DriverManager.getConnection(host);
            PreparedStatement prest;
            //SQL
            String sql = "select students_results.assment_1,students_results.assment_2,students_results.assment_3,students_results.exam,students_results.grade"
                    + " from students_results where students_results.student_id = ?;";

            prest = conn.prepareStatement(sql);
            prest.setString(1, studentIdLi.getSelectedItem().toString());
            //Results of the sql stored in the resultSet rs1
            ResultSet rs1 = prest.executeQuery();
            //This will loop and show all the results from the sql query
            while (rs1.next()){

                assmentsLi.add((rs1.getObject(1)+"")+ " " + (rs1.getObject(2)+"")+ " " + (rs1.getObject(3)+""));
                examsLi.add((rs1.getObject(4)+""));
                gradeLi.add((rs1.getObject(5)+""));
                
            }
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
        
    }//GEN-LAST:event_searchBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
            String url = "jdbc:mysql://127.0.0.1:3306/";
            String dbName = "college";
            String driver = "com.mysql.jdbc.Driver";
            String userName = "root";
            String password = "987456321Dc";
            //Class.forName(driver).newInstance();
            Connection conn = DriverManager.getConnection(url+dbName,userName,password);
            //Connection con = DriverManager.getConnection(host);
            PreparedStatement prest;
            //SQL
            String sql = "SELECT student_id FROM college.students;";

            prest = conn.prepareStatement(sql);
            //Results of the sql stored in the resultSet rs1
            ResultSet rs1 = prest.executeQuery();
            //This will loop and show all the results from the sql query
            while (rs1.next()){

                String student_id = rs1.getString(1);
                String value = ("Student Id  : " + student_id );
                System.out.println( value);
                studentIdLi.add((rs1.getObject(1)+""));
            }
        }
        catch (SQLException err) {
            System.out.println(err.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        studentNameLi.removeAll();
        classGroupLi.removeAll();
        modulesLi.removeAll();
        assmentsLi.removeAll();
        examsLi.removeAll();
        gradeLi.removeAll();
    }//GEN-LAST:event_clearBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showStudentRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showStudentRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showStudentRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showStudentRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showStudentRecordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List assmentsLi;
    private java.awt.List classGroupLi;
    private javax.swing.JButton clearB;
    private java.awt.List examsLi;
    private java.awt.List gradeLi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton menuB;
    private java.awt.List modulesLi;
    private javax.swing.JButton searchB;
    private java.awt.List studentIdLi;
    private java.awt.List studentNameLi;
    // End of variables declaration//GEN-END:variables
}
