/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author disen
 */
public class main extends javax.swing.JFrame {


    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }
floorStaff fs1 = new floorStaff();
manger m1 = new manger();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffCb = new javax.swing.JComboBox<>();
        nameL = new javax.swing.JLabel();
        addressL = new javax.swing.JLabel();
        payroleNoL = new javax.swing.JLabel();
        ppsnL = new javax.swing.JLabel();
        rateOfPayL = new javax.swing.JLabel();
        hoursL = new javax.swing.JLabel();
        yearsOfSerivesL = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        addressTf = new javax.swing.JTextField();
        payroleNoTf = new javax.swing.JTextField();
        ppsnTf = new javax.swing.JTextField();
        rateOfPayTf = new javax.swing.JTextField();
        yearsInServesTf = new javax.swing.JTextField();
        hoursTf = new javax.swing.JTextField();
        savefsB = new javax.swing.JButton();
        viewfsB = new javax.swing.JButton();
        savemB = new javax.swing.JButton();
        viewmB = new javax.swing.JButton();
        selectB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Floorstaff", "Manger" }));
        jPanel1.add(staffCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, -1, -1));

        nameL.setText("Name");
        jPanel1.add(nameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, 39, -1));

        addressL.setText("Address");
        jPanel1.add(addressL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));

        payroleNoL.setText("Payrole No");
        jPanel1.add(payroleNoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        ppsnL.setText("PPSN");
        jPanel1.add(ppsnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, -1, -1));

        rateOfPayL.setText("Rate of Pay");
        rateOfPayL.setVisible(false);
        jPanel1.add(rateOfPayL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));

        hoursL.setText("Hours");
        hoursL.setVisible(false);
        jPanel1.add(hoursL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        yearsOfSerivesL.setText("Years of Serives");
        yearsOfSerivesL.setVisible(false);
        jPanel1.add(yearsOfSerivesL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(nameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 230, -1));
        jPanel1.add(addressTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 230, -1));
        jPanel1.add(payroleNoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 230, -1));
        jPanel1.add(ppsnTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 230, -1));

        rateOfPayTf.setVisible(false);
        jPanel1.add(rateOfPayTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 230, -1));

        yearsInServesTf.setVisible(false);
        jPanel1.add(yearsInServesTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 180, 230, -1));

        hoursTf.setVisible(false);
        jPanel1.add(hoursTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 230, -1));

        savefsB.setText("save");
        savefsB.setVisible(false);
        savefsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savefsBActionPerformed(evt);
            }
        });
        jPanel1.add(savefsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        viewfsB.setText("view");
        viewfsB.setVisible(false);
        viewfsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfsBActionPerformed(evt);
            }
        });
        jPanel1.add(viewfsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        savemB.setText("save");
        savemB.setVisible(false);
        savemB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savemBActionPerformed(evt);
            }
        });
        jPanel1.add(savemB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        viewmB.setText("view");
        viewmB.setVisible(false);
        viewmB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmBActionPerformed(evt);
            }
        });
        jPanel1.add(viewmB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        selectB.setText("Select");
        selectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBActionPerformed(evt);
            }
        });
        jPanel1.add(selectB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savemBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savemBActionPerformed
         m1.setName(nameTf.getText());
         m1.setAddress(addressTf.getText());
         m1.setPayRoleNo(payroleNoTf.getText());
         m1.setPpsn(ppsnTf.getText());
         m1.setYearsOfServies(yearsInServesTf.getText());
         m1.getCalculateSalery();
    }//GEN-LAST:event_savemBActionPerformed

    private void savefsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savefsBActionPerformed
         fs1.setName(nameTf.getText());
         fs1.setAddress(addressTf.getText());
         fs1.setPayRoleNo(payroleNoTf.getText());
         fs1.setPpsn(ppsnTf.getText());
         fs1.setRate(rateOfPayTf.getText());
         fs1.setHours(hoursTf.getText());
         fs1.setCalculateWages();
    }//GEN-LAST:event_savefsBActionPerformed

    private void viewfsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewfsBActionPerformed
        JOptionPane.showMessageDialog(null,fs1.getName()+"\n"+fs1.getAddress()+"\n"+fs1.getPayRoleNo()+"\n"+fs1.getPpsn()+"\n"+fs1.getCalculatedWage());
    }//GEN-LAST:event_viewfsBActionPerformed

    private void viewmBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmBActionPerformed
        JOptionPane.showMessageDialog(null,m1.getName()+"\n"+m1.getAddress()+"\n"+m1.getPayRoleNo()+"\n"+m1.getPpsn()+"\n"+m1.getCalculateSalery());
    }//GEN-LAST:event_viewmBActionPerformed

    private void selectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBActionPerformed
        String selection = (String) staffCb.getSelectedItem();
        
        if(selection.equals("Floorstaff")){
            rateOfPayL.setVisible(true);
            rateOfPayTf.setVisible(true);
            hoursL.setVisible(true);
            hoursTf.setVisible(true);
            savefsB.setVisible(true);
            viewfsB.setVisible(true);
            yearsInServesTf.setVisible(false);
            yearsOfSerivesL.setVisible(false);
            savemB.setVisible(false);
            viewmB.setVisible(false);
        }
        if(selection.equals("Manger")){
            rateOfPayL.setVisible(false);
            rateOfPayTf.setVisible(false);
            hoursL.setVisible(false);
            hoursTf.setVisible(false);
            savefsB.setVisible(false);
            viewfsB.setVisible(false);
            yearsInServesTf.setVisible(true);
            yearsOfSerivesL.setVisible(true);
            savemB.setVisible(true);
            viewmB.setVisible(true);
        }
    }//GEN-LAST:event_selectBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressL;
    private javax.swing.JTextField addressTf;
    private javax.swing.JLabel hoursL;
    private javax.swing.JTextField hoursTf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel payroleNoL;
    private javax.swing.JTextField payroleNoTf;
    private javax.swing.JLabel ppsnL;
    private javax.swing.JTextField ppsnTf;
    private javax.swing.JLabel rateOfPayL;
    private javax.swing.JTextField rateOfPayTf;
    private javax.swing.JButton savefsB;
    private javax.swing.JButton savemB;
    private javax.swing.JButton selectB;
    private javax.swing.JComboBox<String> staffCb;
    private javax.swing.JButton viewfsB;
    private javax.swing.JButton viewmB;
    private javax.swing.JTextField yearsInServesTf;
    private javax.swing.JLabel yearsOfSerivesL;
    // End of variables declaration//GEN-END:variables
}
