/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingMachine;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author disen
 */
public class mainMenu extends javax.swing.JFrame {

    private JButton okB;
    private JLabel panle1L;
    private JLabel imageL;
    private JTextField infoTf;
    private JPanel jPanel1;
    private JButton key0B;
    private JButton key1B;
    private JButton key2B;
    private JButton key3B;
    private JButton key4B;
    private JButton key5B;
    private JButton key6B;
    private JButton key7B;
    private JButton key8B;
    private JButton key9B;
    private JButton keyXB;
    private JLabel panle2L;

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoTf = new javax.swing.JTextField();
        imageL = new javax.swing.JLabel();
        panle1L = new javax.swing.JLabel();
        okB = new javax.swing.JButton();
        key0B = new javax.swing.JButton();
        key1B = new javax.swing.JButton();
        key2B = new javax.swing.JButton();
        key3B = new javax.swing.JButton();
        key4B = new javax.swing.JButton();
        key5B = new javax.swing.JButton();
        key6B = new javax.swing.JButton();
        key7B = new javax.swing.JButton();
        key8B = new javax.swing.JButton();
        key9B = new javax.swing.JButton();
        keyXB = new javax.swing.JButton();
        panle2L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "main menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(51, 153, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 51, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoTf.setEditable(false);
        infoTf.setBackground(new java.awt.Color(0, 0, 0));
        infoTf.setForeground(new java.awt.Color(51, 255, 0));
        infoTf.setName(""); // NOI18N
        jPanel1.add(infoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 113, -1, -1));

        imageL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 2.jpg"))); // NOI18N
        jPanel1.add(imageL, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 26, -1, -1));

        panle1L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,2,1.jpg"))); // NOI18N
        jPanel1.add(panle1L, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 26, -1, -1));

        okB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,ok.jpg"))); // NOI18N
        okB.setAlignmentY(0.0F);
        okB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBActionPerformed(evt);
            }
        });
        jPanel1.add(okB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 60, 20));

        key0B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,0.jpg"))); // NOI18N
        key0B.setBorderPainted(false);
        key0B.setPreferredSize(new java.awt.Dimension(17, 17));
        key0B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key0BActionPerformed(evt);
            }
        });
        jPanel1.add(key0B, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        key1B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,1.jpg"))); // NOI18N
        key1B.setAlignmentY(0.0F);
        key1B.setBorder(null);
        key1B.setBorderPainted(false);
        key1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key1BActionPerformed(evt);
            }
        });
        jPanel1.add(key1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 265, 20, -1));

        key2B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,2.jpg"))); // NOI18N
        key2B.setBorderPainted(false);
        key2B.setMaximumSize(new java.awt.Dimension(17, 17));
        key2B.setMinimumSize(new java.awt.Dimension(17, 17));
        key2B.setPreferredSize(new java.awt.Dimension(17, 17));
        key2B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key2BActionPerformed(evt);
            }
        });
        jPanel1.add(key2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 265, -1, -1));

        key3B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,3.jpg"))); // NOI18N
        key3B.setAlignmentY(0.0F);
        key3B.setBorderPainted(false);
        key3B.setMaximumSize(new java.awt.Dimension(17, 17));
        key3B.setMinimumSize(new java.awt.Dimension(17, 17));
        key3B.setPreferredSize(new java.awt.Dimension(17, 17));
        key3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3BActionPerformed(evt);
            }
        });
        jPanel1.add(key3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 265, 20, -1));

        key4B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,4.jpg"))); // NOI18N
        key4B.setAlignmentY(0.0F);
        key4B.setBorderPainted(false);
        key4B.setMargin(new java.awt.Insets(0, 0, 0, 0));
        key4B.setMaximumSize(new java.awt.Dimension(17, 17));
        key4B.setMinimumSize(new java.awt.Dimension(17, 17));
        key4B.setPreferredSize(new java.awt.Dimension(17, 17));
        key4B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key4BActionPerformed(evt);
            }
        });
        jPanel1.add(key4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 283, -1, -1));

        key5B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,5.jpg"))); // NOI18N
        key5B.setAlignmentY(0.0F);
        key5B.setBorder(null);
        key5B.setBorderPainted(false);
        key5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key5BActionPerformed(evt);
            }
        });
        jPanel1.add(key5B, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 283, -1, -1));

        key6B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,6.jpg"))); // NOI18N
        key6B.setAlignmentY(0.0F);
        key6B.setBorderPainted(false);
        key6B.setMaximumSize(new java.awt.Dimension(17, 17));
        key6B.setMinimumSize(new java.awt.Dimension(17, 17));
        key6B.setPreferredSize(new java.awt.Dimension(17, 17));
        key6B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key6BActionPerformed(evt);
            }
        });
        jPanel1.add(key6B, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 283, -1, -1));

        key7B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,7.jpg"))); // NOI18N
        key7B.setAlignmentY(0.0F);
        key7B.setBorderPainted(false);
        key7B.setMaximumSize(new java.awt.Dimension(17, 17));
        key7B.setMinimumSize(new java.awt.Dimension(17, 17));
        key7B.setPreferredSize(new java.awt.Dimension(17, 17));
        key7B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key7BActionPerformed(evt);
            }
        });
        jPanel1.add(key7B, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 302, -1, -1));

        key8B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,8.jpg"))); // NOI18N
        key8B.setBorderPainted(false);
        key8B.setPreferredSize(new java.awt.Dimension(17, 17));
        key8B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key8BActionPerformed(evt);
            }
        });
        jPanel1.add(key8B, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 302, -1, -1));

        key9B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,9.jpg"))); // NOI18N
        key9B.setBorderPainted(false);
        key9B.setPreferredSize(new java.awt.Dimension(17, 17));
        key9B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key9BActionPerformed(evt);
            }
        });
        jPanel1.add(key9B, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 302, -1, -1));

        keyXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1,x.jpg"))); // NOI18N
        keyXB.setBorderPainted(false);
        keyXB.setPreferredSize(new java.awt.Dimension(17, 17));
        keyXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyXBActionPerformed(evt);
            }
        });
        jPanel1.add(keyXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        panle2L.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingMachine/merchant204_combiplusfood 3,1,1.jpg"))); // NOI18N
        panle2L.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(panle2L, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 223, 69, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void key8BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key8BActionPerformed
        infoTf.setText("8");
    }//GEN-LAST:event_key8BActionPerformed

    private void key4BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key4BActionPerformed
        infoTf.setText("4");
    }//GEN-LAST:event_key4BActionPerformed

    private void key0BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key0BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key0BActionPerformed

    private void key1BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key1BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key1BActionPerformed

    private void key2BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key2BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key2BActionPerformed

    private void key3BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key3BActionPerformed

    private void key5BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key5BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key5BActionPerformed

    private void key6BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key6BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key6BActionPerformed

    private void key7BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key7BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key7BActionPerformed

    private void key9BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key9BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key9BActionPerformed

    private void keyXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyXBActionPerformed

    private void okBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//       }// catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            //java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(javakey6Bgging.Level.SEVERE, null, ex);
//        //}
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageL;
    private javax.swing.JTextField infoTf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton key0B;
    private javax.swing.JButton key1B;
    private javax.swing.JButton key2B;
    private javax.swing.JButton key3B;
    private javax.swing.JButton key4B;
    private javax.swing.JButton key5B;
    private javax.swing.JButton key6B;
    private javax.swing.JButton key7B;
    private javax.swing.JButton key8B;
    private javax.swing.JButton key9B;
    private javax.swing.JButton keyXB;
    private javax.swing.JButton okB;
    private javax.swing.JLabel panle1L;
    private javax.swing.JLabel panle2L;
    // End of variables declaration//GEN-END:variables
});
                }          
}
