
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author disen
 */
public class rentMenu extends javax.swing.JFrame {

    /**
     * Creates new form rentMenu
     */
    public rentMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountNumberL = new javax.swing.JLabel();
        accountNumberTf = new javax.swing.JTextField();
        filmL = new javax.swing.JLabel();
        filmTf = new javax.swing.JTextField();
        dayWantedL = new javax.swing.JLabel();
        dayWantedTf = new javax.swing.JTextField();
        rentB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        fimlLi = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTa = new javax.swing.JTextArea();
        chosenFilmL = new javax.swing.JLabel();
        chosenfilmTl = new javax.swing.JLabel();
        priceL = new javax.swing.JLabel();
        priceTl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rent Menu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        accountNumberL.setText("Account number");

        filmL.setText("Film");

        dayWantedL.setText("Day wanted");

        rentB.setText("Rent");
        rentB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBActionPerformed(evt);
            }
        });

        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });

        fimlLi.addItem("Fast and Furious");
        fimlLi.addItem("Death Race");
        fimlLi.addItem("RedLine");
        fimlLi.addItem("Mad Max");
        fimlLi.addItem("Desalition");
        fimlLi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fimlLiMouseClicked(evt);
            }
        });

        descriptionTa.setColumns(20);
        descriptionTa.setRows(5);
        jScrollPane1.setViewportView(descriptionTa);

        chosenFilmL.setText("Chosen fiilm");

        priceL.setText("price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backB)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(rentB, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(fimlLi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dayWantedL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filmL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accountNumberL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(chosenFilmL)
                            .addComponent(priceL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountNumberTf)
                            .addComponent(filmTf)
                            .addComponent(dayWantedTf)
                            .addComponent(chosenfilmTl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceTl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fimlLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priceL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceTl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chosenFilmL)
                    .addComponent(chosenfilmTl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNumberL)
                    .addComponent(accountNumberTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmL)
                    .addComponent(filmTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayWantedL)
                    .addComponent(dayWantedTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rentB)
                .addGap(18, 18, 18)
                .addComponent(backB))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
       this.dispose ();
       mainMenu mainMenuFrame = new mainMenu ();
       mainMenuFrame.setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    private void rentBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBActionPerformed
       String accountNumberj = accountNumberTf.getText ();
       double dayj =Double.parseDouble(dayWantedTf.getText ());
       String filmj = filmTf.getText();
       double pricej =Double.parseDouble(priceTl.getText());
       JOptionPane.showMessageDialog(null ,"aacount number "+ accountNumberj +"\n rented day " +dayj +"\n The film " + filmj);
       this.dispose ();
    }//GEN-LAST:event_rentBActionPerformed

    private void fimlLiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fimlLiMouseClicked
 
    if(fimlLi.getSelectedItem().equals("Fast and Furious")){
   descriptionTa.setText("The Fast and the Furious is an American franchise"+"\n"+"based on a series of action films that is largely concerned with"+"\n"+"illegal street racing and heists,and includes material in various"+"\n"+"other media that depicts characters and situations from the films");
   priceTl.setText("10");
   chosenfilmTl.setText("Fast and Furious");
}
 else if(fimlLi.getSelectedItem().equals("Death Race")){
  descriptionTa.setText("Framed for a murder he did not commit, three-time speedway"+"\n"+"champ Jensen Ames (Jason Statham) finds himself at Terminal Island,"+"\n"+"the country's toughest prison, but he gets an unexpected chance"+"\n"+"at freedom when the warden offers a choice: Compete in the"+"\n"+"Death Race as a mythical driver called Frankenstein, or rot in a cell forever."+"\n"+"Riding in a car equipped with flamethrowers and grenade launchers,"+"\n"+"Ames must survive a gauntlet of vicious criminals to win"+"\n"+"his freedom -- or die trying.");
  priceTl.setText("10");
  chosenfilmTl.setText("Death Race");
 }
 else if(fimlLi.getSelectedItem().equals("RedLine")){
  descriptionTa.setText("A daredevil driver (Takuya Kimura) falls for an alluring woman"+"\n"+"(Yû Aoi) as he tries to win a race that occurs only once every five years.");
  priceTl.setText("10");
  chosenfilmTl.setText("RedLine");
 }
 else if(fimlLi.getSelectedItem().equals("Mad Max")){
  descriptionTa.setText("Years after the collapse of civilization, the tyrannical Immortan Joe enslaves apocalypse survivors inside the desert fortress the Citadel. When the warrior Imperator Furiosa (Charlize Theron) leads the despot's five wives in a daring escape, she forges an alliance with Max Rockatansky (Tom Hardy), a loner and former captive. Fortified in the massive, armored truck the War Rig, they try to outrun the ruthless warlord and his henchmen in a deadly high-speed chase through the Wasteland.");
 }
 else if(fimlLi.getSelectedItem().equals("Desalition")){
  descriptionTa.setText("test5");
 }
    
    }//GEN-LAST:event_fimlLiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rentMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rentMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberL;
    private javax.swing.JTextField accountNumberTf;
    private javax.swing.JButton backB;
    private javax.swing.JLabel chosenFilmL;
    private javax.swing.JLabel chosenfilmTl;
    private javax.swing.JLabel dayWantedL;
    private javax.swing.JTextField dayWantedTf;
    private javax.swing.JTextArea descriptionTa;
    private javax.swing.JLabel filmL;
    private javax.swing.JTextField filmTf;
    private java.awt.List fimlLi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceL;
    private javax.swing.JLabel priceTl;
    private javax.swing.JButton rentB;
    // End of variables declaration//GEN-END:variables
}
